### ISSUE TITLE
bytes32 instead of strings

### ISSUE THREAD

**Issue by Pfed-prog** [TalentLayer/talentlayer-id-contracts#129]
Article for reference: https://medium.com/@cryptopusco/bytes-and-strings-in-solidity-f2cd4e53f388

E.g.
`contracts/tests/TalentLayerIDV2.sol` Profile struct contains string handle attribute which can be changed to bytes32

The line in code
`uint8 constant MAX_HANDLE_LENGTH = 31;`
also satisfies this condition

**Comment by mattiapomelli** [comment]
That's a good point. The problem is that we need the handle as a string for the token uri (see `_buildTokenURI` function), but it's quite tricky to convert a bytes32 to string without knowing the length of the string (and without adding extra zeros as padding)

So probably the change is not worth the extra complexity that it adds.

Thanks for the suggestions though, and would like to hear your thoughts on this. Maybe there's a solution that we are not thinking about.

**Comment by Pfed-prog** [comment]
https://stackoverflow.com/questions/67893318/solidity-how-to-represent-bytes32-as-string

**Comment by Pfed-prog** [comment]
https://akashmittal.com/convert-bytes32-string-solidity/
